### ISSUE TITLE
Header-only library?

### ISSUE THREAD

**Issue by m8pple** [Carotti/lollipopt#1]
Just a suggestion, but given the way the library is constructed you could probably
make it header-only. It generally makes it easier to include in a project, esp. for
utility libraries.

If you don't like inline member functions defs, they could be lifted into a detail
header to avoid cluttering the main class defn. header, similar to how boost
organises its libraries.

**Comment by Carotti** [comment]
It definitely makes more sense to include a single header file than to compile all of the source each time (especially since there isn't a vast amount of code). I'll definitely do this when I get a moment.
